spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/maali}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration de la generation du schema de la base de donnees
spring.jpa.hibernate.ddl-auto=update

# Dialecte SQL specifique a la base de donnees
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Afficher les requetes SQL generees dans les logs
spring.jpa.show-sql=true

# Formatage des requetes SQL dans les logs
spring.jpa.properties.hibernate.format_sql=true

# Utiliser des guillemets autour des noms d'identificateurs (si necessaire)
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
server.port=8081
